# Generated by Django 5.0 on 2024-01-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("final", "0004_rename_billing_name_invoice_billto"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="BCity",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="BState",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="Bzip",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
