# Generated by Django 5.0 on 2024-01-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("final", "0005_invoice_bcity_invoice_bstate_invoice_bzip"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
