# Generated by Django 5.0 on 2024-01-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("final", "0006_invoice_invoice_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="billing_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="company_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
