# Generated by Django 5.0 on 2024-01-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="logo_images/"),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("email", models.CharField(max_length=255)),
                ("company_number", models.IntegerField()),
                ("billing_number", models.IntegerField()),
                ("taxed", models.IntegerField()),
                ("company_address", models.CharField(max_length=255)),
                ("billing_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("zip", models.IntegerField()),
                ("description", models.TextField()),
                ("amount", models.IntegerField()),
                ("quantity", models.IntegerField()),
            ],
        ),
    ]
