# Generated by Django 5.0 on 2024-01-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("final", "0002_invoice_notes_alter_invoice_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="billing_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
