# Generated by Django 5.0 on 2024-01-14 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("final", "0003_invoice_billing_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="billing_name",
            new_name="billTo",
        ),
    ]
