# Generated by Django 5.0 on 2024-01-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("final", "0007_alter_invoice_billing_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="statement",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
