# Generated by Django 5.0 on 2024-01-19 03:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("final", "0009_invoicehistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InvoiceHistory",
        ),
    ]
